devel: birds are flying-13 debian working
git-svn-id: https://svn.code.sf.net/p/xsnow/code/trunk@179 79837d8a-40e5-47fd-869e-05d31bbd7fe9

diff --git a/xsnow-devel/pbuilderscript b/xsnow-devel/pbuilderscript
--- a/xsnow-devel/pbuilderscript
+++ b/xsnow-devel/pbuilderscript
@@ -7,34 +7,50 @@ if [ -z "$3" ] ; then
    echo usage: pbuilderscript workdir oldversion newversion
    exit 1
 fi
+if [ x$PBUILDER_OPERATION != x ] ; then
+   sed -i '0,/^#deb-src/s/^#//' /etc/apt/sources.list
+   apt update
+fi
 cd "$workdir" || exit 1
 echo "working in `pwd`"
 export DEBEMAIL=wvermin@gmail.com
 export DEBFULLNAME="Willem Vermin"
-sed -i 's/^#//;s/$/ non-free/' /etc/apt/sources.list   # oncomment 2de regel
-apt update
 apt -y install apt-utils || exit 1
 apt -y install quilt devscripts debhelper autotools-dev equivs || exit 1
 apt source xsnow || exit 1
 cd xsnow-$oldversion || exit 1
 uupdate -v $newversion ../xsnow-$newversion.tar.gz || exit 1
 cd ../xsnow-$newversion
-if [ -d debian.upstream ] ; then
-   rm -r debian
+if [ -d debian.upstream ] ; then       
+   rm -r debian                     # staan hier .buildinfo en .changes?
    mv debian.upstream debian || exit 1
 fi
-#apt -y install vim
-#echo dpkg-source ...
-#dpkg-source --commit
 echo quilt ...
 while quilt push; do quilt refresh; done
 #dch
 echo "---------- mk-build-deps -----------------"
 echo | mk-build-deps -i -r debian/control || exit 1
-#dpkg-source --commit
-#while quilt push; do quilt refresh; done
+# got dpkg-source: error: aborting due to unexpected upstream changes
+# caused by the files *-build-deps*.buildinfo and *-build-deps*.changes
+# created by mk-build-deps
+# hence the following:
+if true ; then
+   # this seems to be the recommended way
+   mkdir -p debian/source
+   (
+   echo "Description: to remedy this"
+   echo "  dpkg-source: error: aborting due to unexpected upstream changes"
+   echo "Forwarded: not-needed"
+   ) > debian/source/local-patch-header
+   EDITOR=/bin/true dpkg-source --commit . buildinfo-changes
+   while quilt push; do quilt refresh; done
+   #
+else
+   # simple remove the offending files
+   rm -f *-build-deps*.buildinfo *-build-deps*.changes
+fi
 echo "-------------- dpkg-buildpackage ------------"
-dpkg-buildpackage -us -uc
+dpkg-buildpackage -us -uc || exit 1
 cd ..
 echo "running lintian ..."
 lintian -i -I --show-overrides xsnow_$newversion-1_amd64.changes
